spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waltr?useSSL=false&serverTimezone=UTC
    username: root
    password: test

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update